name: .NET

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        configuration: [debug, release]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c ${{ matrix.configuration }} --no-restore
    - name: Test
      run: dotnet test -c ${{ matrix.configuration }} --no-build --verbosity normal

  publish:

    runs-on: ubuntu-latest

    needs: [build]

    strategy:
      matrix:
        runtime: [win-x64, win-x86, win-arm, win-arm64, linux-x64, linux-arm, linux-arm64, osx-x64]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run: dotnet publish -c release -r ${{ matrix.runtime }} --self-contained false -p:PublishSingleFile=true -p:UseAppHost=true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: scaffold-${{ matrix.runtime }}
        path: |
          src/Scaffold/bin/Release/net5.0/${{ matrix.runtime }}/publish/Scaffold
          src/Scaffold/bin/Release/net5.0/${{ matrix.runtime }}/publish/Scaffold.exe
    - name: Create a release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          src/Scaffold/bin/Release/net5.0/${{ matrix.runtime }}/publish/Scaffold
          src/Scaffold/bin/Release/net5.0/${{ matrix.runtime }}/publish/Scaffold.exe
      env:
        GITHUB_TOKEN: ${{ github.token }}
